#! /bin/sh
### BEGIN INIT INFO
# Provides:          FastCGI servers for Django
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: Start FastCGI servers with Django.
# Description:       Django, in order to operate with FastCGI, must be started
#                    in a very specific way with manage.py. This must be done
#                    for each DJango web server that has to run.
### END INIT INFO
#
# Author:  Guillermo Fernandez Castellanos
#          <guillermo.fernandez.castellanos AT gmail.com>.
#
# Version: @(#)fastcgi 0.1 11-Jan-2007 guillermo.fernandez.castellanos AT gmail.com
#

#### SERVER SPECIFIC CONFIGURATION
RADIATOR_PATH=/opt/jenkins-radiator/jenkins_radiator
RADIATOR_PID=$RADIATOR_PATH/radiator.pid
HOST=0.0.0.0
PORT_START=8803
RUN_AS=hudson
FCGI_METHOD=prefork
#### DO NOT CHANGE ANYTHING AFTER THIS LINE!

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME="jenkins-radiator"
DESC="Jenkins Radiator"

#
#       Function that starts the daemon/service.
#
d_start()
{
        echo -n "$SITE"
        if [ -f $RADIATOR_PID ]; then
            echo -n " already running"
        else
            start-stop-daemon --start --quiet \
                       --pidfile $RADIATOR_PID \
                       --chuid $RUN_AS --exec /usr/bin/env -- python \
                       $RADIATOR_PATH/$SITE/manage.py runfcgi \
                       method=$FCGI_METHOD \
                       host=$HOST port=$PORT pidfile=$RADIATOR_PID
            chmod 400 $RADIATOR_PID
        fi

}

#
#       Function that stops the daemon/service.
#
d_stop() {
    # Killing all Django FastCGI processes running
        echo -n "$SITE"
        start-stop-daemon --stop --quiet --pidfile $RADIATOR_PID \
                          || echo -n " not running"
        if [ -f $RADIATOR_PID ]; then
           rm -f $RADIATOR_PID
        fi
    done
}

ACTION="$1"
case "$ACTION" in
    start)
        echo -n "Starting $DESC: $NAME"
        d_start
        echo "."
        ;;

    stop)
        echo -n "Stopping $DESC: $NAME"
        d_stop
        echo "."
        ;;

    restart|force-reload)
        echo -n "Restarting $DESC: $NAME"
        d_stop
        sleep 1
        d_start
        echo "."
        ;;

    *)
        echo "Usage: $NAME {start|stop|restart|force-reload}" >&2
        exit 3
        ;;
esac

exit 0